### ISSUE TITLE
put does't work

### ISSUE THREAD

**Issue by ghost** [martsve/mkm_api#2]
put doesn't work: returns 417

**Comment by martsve** [comment]
Works for me. Try:

```
mkm put account/vacation/false
```

**Comment by martsve** [comment]
I just tried to do this after adding an item to my cart. :

```
mkm-api put shoppingcart/shippingaddress -f ship.xml
```

with ship.xml haivng the content of the example at https://www.mkmapi.eu/ws/documentation/API_1.1:ShoppingCart_ShippingAddress

It also worked. You probably have incorrectly formated XML.
