### ISSUE TITLE
STOCK

### ISSUE THREAD

**Issue by RoostyZT123** [martsve/mkm_api#4]
Hello,

first i would like to thank you for your project, it helps me a lot :)

But i am having some problems using the "MKM GET stock" command.

It returns empty XML:
[ZACSQ.txt](https://github.com/martsve/mkm_api/files/1843232/ZACSQ.txt)

I have my tokens.txt file in the same directory and it everything works fine for all the other command.

Tell me please, am i doing something wrong ?

Thank you

**Comment by martsve** [comment]
Since you are getting a response with valid data from Cardmarket, the issue would either be with your stock, or with Cardmarket.

The stock is the files you have availible to sell. The response you posted would indicate that you do not have any cards for sale.
