### ISSUE TITLE
DELETE stock not working

### ISSUE THREAD

**Issue by jaskamakkara** [martsve/mkm_api#5]
Hi,

I'm having a hard time getting the DELETE stock function to work. I get a 400 error back every time. I'm trying to delete only a few articles at a time, so I'm not going over the 100 article limit. I am calling the function like this:

`mkm del stock -f DeleteList.xml`

I've been able to effectively delete the articles by using the stock/decrease function and the same DeleteList.xml file, but I'm wondering why delete doesn't work. I'm sure that my file is in the same format as the example on the documentation webpage, but am I understanding Delete wrongly somehow?

**Comment by martsve** [comment]
There does not seem to be a DELETE /stock endpoint in the documentation that takes a file as input:

https://api.cardmarket.com/ws/documentation/API_2.0:Stock_Management
https://api.cardmarket.com/ws/documentation/API_1.1:Stock_Management

If you need that kind of functionallity I guess you would have to contact Cardmarket and ask if they would be willing to add such functionallity.
