### ISSUE TITLE
Delete Stock

### ISSUE THREAD

**Issue by jaskamakkara** [martsve/mkm_api#6]
Hi, I posted about this a while ago, and I've come back to it now:

There doesn't seem to be the DELETE functionality that the API supports. You said before that the API doesn't support it, but example 5 of this page shows it:

[MKM API 2.0 Documentation](https://api.cardmarket.com/ws/documentation/API_2.0:Stock)

Would this be easy to implement? Otherwise, I'm having a great time with this and it works really well, I appreciate the hard work you've put into it.

Thanks

**Comment by martsve** [comment]
Works fine for me. Maybe you are using an old .exe file version? I've updated the one in the repo just in case.

_Contents of s.xml:_
```
<?xml version="1.0" encoding="UTF-8" ?>
<request>
    <article>
        <idArticle>304209292</idArticle>
        <count>1</count>
    </article>
</request>
```

**mkm del stock -f s.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<response>
  <deleted>
    <idArticle>304209292</idArticle>
    <count>1</count>
    <success>true</success>
  </deleted>
</response>
```

**Comment by jaskamakkara** [comment]
Yes, I tried it with the new exe and it works. Thanks.
