### ISSUE TITLE
Executable not terminating

### ISSUE THREAD

**Issue by jaskamakkara** [martsve/mkm_api#7]
Hi, I am having a new problem with the new exe file. When I run mkm.exe from the command line it doesn't automatically terminate the program when it's done - I have to press enter again to get back to the prompt. This is an issue since I am running the program from a Visual Basic script and my program ends up hanging indefinitely after running mkm.exe. I didn't have this problem with the older executable. Is there a way to fix this?

**Comment by martsve** [comment]
Sorry, I uploaded the debug version instead of the relase version. It has now been updated.
